[2023-12-18 18:40:00.826665] -- Ошибка в func_with_exception : Что-то идет не так!
[2023-12-18 18:40:00.827157] -- Ошибка в func_with_exception_two : Что-то идет не так 2!
